version: '3'

services: 
  nginx:
    container_name: nginx
    restart: unless-stopped
    env_file: 
      - .env
    networks: 
      - connect
    depends_on:
      - wordpress
    build: requirements/nginx/
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wp-data:/www

  ftp:
    container_name: ftp
    build: requirements/bonus/ftp/
    restart: unless-stopped
    image: ftp
    env_file:
        - .env
    volumes:
        - wp-data:/home/abkssiba
    ports:
        - "21:21"
        - "10000:10000"
    depends_on:
      - wordpress
    networks: 
      - connect

  wordpress:
    container_name: wordpress
    restart: unless-stopped
    env_file: 
      - .env
    networks: 
      - connect
    depends_on:
      - mariadb
      - redis
    build: requirements/wordpress/
    image: wordpress
    volumes:
      - wp-data:/www

  mariadb:
    container_name: mariadb
    restart: unless-stopped
    env_file: 
      - .env
    networks: 
      - connect
    build: requirements/mariadb/
    image: mariadb
    volumes: 
      - db-data:/var/lib/mysql
  
  adminer:
    container_name: adminer
    restart: unless-stopped
    env_file: 
      - .env
    networks: 
      - connect
    ports:
      - "5555:5555"
    build: requirements/bonus/adminer/
    image: adminer

  redis:
    container_name: redis
    build: requirements/bonus/redis/
    image: redis
    restart: unless-stopped
    networks:
      - connect

  website:
    container_name: website
    restart: unless-stopped
    env_file:
      - .env
    build: requirements/bonus/website/
    image: website
    ports:
      - "9999:9999"

  backup:
    container_name: backup
    image: backup
    restart: unless-stopped
    depends_on:
        - wordpress
    build: requirements/bonus/backup/
    volumes:
        - backup-data:/backup
        - wp-data:/wp-data
        - db-data:/db-data

volumes:
    wp-data:
      driver: local
      driver_opts:
          type: none
          device: "/home/abkssiba/data/wp-data"
          o: bind
    db-data:
      driver: local
      driver_opts:
        type: none
        device: "/home/abkssiba/data/db-data"
        o: bind
    backup-data:
      driver: local
      driver_opts:
        type: none
        device: "/home/abkssiba/data/backup-data"
        o: bind 

networks:
  connect:
    driver: bridge